import React, { useState, useEffect } from 'react';
import { X, FileText, AlertCircle } from 'lucide-react';
import {
  BillingFeeAgreement,
  BillingFeeAgreementFormData,
  BillingFeeAgreementStatus,
  BillingFrequency,
  BillingMethod
} from '../types/BillingFeeAgreement';
import { FeeSchedule } from '../types/FeeSchedule';
import { Relationship } from '../types/Relationship';
import { Client } from '../types/Client';

interface BillingFeeAgreementFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (agreement: BillingFeeAgreementFormData, householdAccountFeeSchedules?: { [householdId: string]: { [accountId: string]: string } }) => void;
  agreement: BillingFeeAgreement | null;
  availableFeeSchedules: FeeSchedule[]; // Real fee schedules from database
  availableRelationships: Relationship[]; // Real relationships from database
  availableClients: Client[]; // Real clients from database
  availableAccounts: any[]; // Real accounts from database
  availableHouseholds: any[]; // Real households from database
  existingAgreements: BillingFeeAgreement[]; // Existing agreements to filter out assigned households
}

const BillingFeeAgreementFormModal: React.FC<BillingFeeAgreementFormModalProps> = ({
  isOpen,
  onClose,
  onSave,
  agreement,
  availableFeeSchedules,
  availableRelationships,
  availableClients,
  availableAccounts,
  availableHouseholds,
  existingAgreements
}) => {
  // Use real data passed as props instead of mock data
  const feeSchedules = availableFeeSchedules || [];
  const relationships = availableRelationships || [];
  const clients = availableClients || [];
  const allAccounts = availableAccounts || [];
  const allHouseholds = availableHouseholds || [];

  // Filter out households that already have active BFAs (unless we're editing)
  const assignedHouseholdIds = new Set<string>();
  existingAgreements.forEach(bfa => {
    // Skip the current agreement if we're editing
    if (agreement && bfa.id === agreement.id) return;
    // Only filter out households from active agreements
    if (bfa.status === BillingFeeAgreementStatus.ACTIVE) {
      bfa.householdIds.forEach(householdId => assignedHouseholdIds.add(householdId));
    }
  });
  const households = allHouseholds.filter(household => !assignedHouseholdIds.has(household.id));

  console.log('BillingFeeAgreementFormModal - Fee Schedules:', feeSchedules.length, feeSchedules);
  console.log('BillingFeeAgreementFormModal - Households:', households.length, households);
  console.log('BillingFeeAgreementFormModal - Accounts:', allAccounts.length, allAccounts);

  const [formData, setFormData] = useState<BillingFeeAgreementFormData>({
    agreementNumber: '', // Will be auto-generated by database
    status: BillingFeeAgreementStatus.ACTIVE,
    feeScheduleId: '',
    billingFrequency: BillingFrequency.QUARTERLY,
    billingMethod: BillingMethod.ARREARS,
    householdIds: [],
    accountIds: [],
    effectiveDate: new Date(),
    relationshipId: undefined,
    primaryContactClientId: undefined,
    customFeeAdjustment: undefined,
    notes: ''
  });

  // Track selected households
  const [selectedHouseholdIds, setSelectedHouseholdIds] = useState<Set<string>>(new Set());

  // Track account-to-fee-schedule mappings per household: { householdId: { accountId: feeScheduleId } }
  const [householdAccountFeeSchedules, setHouseholdAccountFeeSchedules] = useState<{ [householdId: string]: { [accountId: string]: string } }>({});

  const [errors, setErrors] = useState<{ [key: string]: string }>({});

  useEffect(() => {
    if (agreement) {
      setFormData({
        id: agreement.id,
        agreementNumber: agreement.agreementNumber,
        status: agreement.status,
        feeScheduleId: agreement.feeScheduleId,
        billingFrequency: agreement.billingFrequency,
        billingMethod: agreement.billingMethod,
        billingDay: agreement.billingDay,
        relationshipId: agreement.relationshipId,
        householdIds: agreement.householdIds,
        accountIds: agreement.accountIds,
        primaryContactClientId: agreement.primaryContactClientId,
        customFeeAdjustment: agreement.customFeeAdjustment,
        customFeeAdjustmentNotes: agreement.customFeeAdjustmentNotes,
        effectiveDate: agreement.effectiveDate,
        terminationDate: agreement.terminationDate,
        notes: agreement.notes || '',
        internalNotes: agreement.internalNotes
      });
      // When editing, populate household and account-fee schedule mappings
      const newSelectedHouseholds = new Set(agreement.householdIds);
      setSelectedHouseholdIds(newSelectedHouseholds);

      // Group accounts by household and set fee schedules
      const householdMappings: { [householdId: string]: { [accountId: string]: string } } = {};
      agreement.householdIds.forEach(householdId => {
        householdMappings[householdId] = {};
        // Set the same fee schedule for all accounts in this household (when editing existing BFA)
        agreement.accountIds.forEach(accountId => {
          const account = allAccounts.find(a => a.id === accountId);
          if (account && account.householdId === householdId) {
            householdMappings[householdId][accountId] = agreement.feeScheduleId;
          }
        });
      });
      setHouseholdAccountFeeSchedules(householdMappings);
    } else {
      setFormData({
        agreementNumber: '', // Will be auto-generated
        status: BillingFeeAgreementStatus.ACTIVE,
        feeScheduleId: '',
        billingFrequency: BillingFrequency.QUARTERLY,
        billingMethod: BillingMethod.ARREARS,
        householdIds: [],
        accountIds: [],
        effectiveDate: new Date(),
        relationshipId: undefined,
        primaryContactClientId: undefined,
        customFeeAdjustment: undefined,
        notes: ''
      });
      setSelectedHouseholdIds(new Set());
      setHouseholdAccountFeeSchedules({});
    }
    setErrors({});
  }, [agreement, isOpen, allAccounts]);

  const handleChange = (field: keyof BillingFeeAgreementFormData, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));

    // Clear error for this field
    if (errors[field]) {
      setErrors(prev => {
        const newErrors = { ...prev };
        delete newErrors[field];
        return newErrors;
      });
    }
  };

  const validate = (): boolean => {
    const newErrors: { [key: string]: string } = {};

    // Check if at least one household is selected
    if (selectedHouseholdIds.size === 0) {
      newErrors.households = 'At least one household is required';
    }

    // Check that each account in selected households has a fee schedule assigned
    selectedHouseholdIds.forEach(householdId => {
      const household = households.find(h => h.id === householdId);
      if (!household) return;

      const householdAccounts = allAccounts.filter(acc => acc.householdId === householdId);
      const accountMappings = householdAccountFeeSchedules[householdId] || {};

      householdAccounts.forEach(account => {
        if (!accountMappings[account.id]) {
          newErrors[`account_${account.id}`] = `${account.accountNumber} must have a fee schedule selected`;
        }
      });
    });

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (validate()) {
      onSave(formData, householdAccountFeeSchedules);
    }
  };

  // Handle household selection toggle
  const handleHouseholdToggle = (householdId: string) => {
    setSelectedHouseholdIds(prev => {
      const newSet = new Set(prev);
      if (newSet.has(householdId)) {
        // Deselect: remove household
        newSet.delete(householdId);
        // Also remove all account mappings for this household
        setHouseholdAccountFeeSchedules(prevMappings => {
          const newMappings = { ...prevMappings };
          delete newMappings[householdId];
          return newMappings;
        });
      } else {
        // Select: add household and initialize account mappings
        newSet.add(householdId);
        setHouseholdAccountFeeSchedules(prevMappings => ({
          ...prevMappings,
          [householdId]: {}
        }));
      }
      return newSet;
    });

    // Clear errors for this household
    if (errors[`household_${householdId}`]) {
      setErrors(prev => {
        const newErrors = { ...prev };
        delete newErrors[`household_${householdId}`];
        return newErrors;
      });
    }
  };

  // Handle fee schedule selection for a specific account within a household
  const handleAccountFeeScheduleChange = (householdId: string, accountId: string, feeScheduleId: string) => {
    setHouseholdAccountFeeSchedules(prev => ({
      ...prev,
      [householdId]: {
        ...(prev[householdId] || {}),
        [accountId]: feeScheduleId
      }
    }));

    // Clear errors for this account
    if (errors[`account_${accountId}`]) {
      setErrors(prev => {
        const newErrors = { ...prev };
        delete newErrors[`account_${accountId}`];
        return newErrors;
      });
    }
  };

  if (!isOpen) return null;

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1000,
      padding: '20px'
    }}>
      <div style={{
        backgroundColor: 'white',
        borderRadius: '12px',
        width: '700px',
        maxWidth: '100%',
        maxHeight: '90vh',
        display: 'flex',
        flexDirection: 'column'
      }}>
        {/* Header */}
        <div style={{
          padding: '24px',
          borderBottom: '1px solid #e0e0e0',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div style={{
              width: '40px',
              height: '40px',
              borderRadius: '50%',
              backgroundColor: '#e3f2fd',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center'
            }}>
              <FileText size={20} color="#2196f3" />
            </div>
            <h2 style={{ fontSize: '20px', fontWeight: 'bold', margin: 0 }}>
              {agreement ? 'Edit Billing Fee Agreement' : 'Add New Billing Fee Agreement'}
            </h2>
          </div>
          <button
            onClick={onClose}
            style={{
              padding: '8px',
              backgroundColor: 'transparent',
              border: 'none',
              cursor: 'pointer',
              borderRadius: '4px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center'
            }}
          >
            <X size={20} color="#666" />
          </button>
        </div>

        {/* Content */}
        <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', flex: 1, overflow: 'hidden' }}>
          <div style={{ padding: '24px', overflowY: 'auto', flex: 1 }}>
            {/* Basic Information */}
            <div style={{ marginBottom: '24px' }}>
              <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '16px', color: '#333' }}>
                Basic Information
              </h3>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '16px' }}>
                {agreement && (
                  <div>
                    <label style={{
                      display: 'block',
                      fontSize: '13px',
                      fontWeight: 'bold',
                      marginBottom: '8px',
                      color: '#333'
                    }}>
                      Agreement Number
                    </label>
                    <input
                      type="text"
                      value={formData.agreementNumber}
                      disabled
                      style={{
                        width: '100%',
                        padding: '10px',
                        border: '1px solid #ddd',
                        borderRadius: '6px',
                        fontSize: '14px',
                        backgroundColor: '#f5f5f5',
                        color: '#666',
                        cursor: 'not-allowed'
                      }}
                    />
                    <p style={{ fontSize: '11px', color: '#999', marginTop: '4px' }}>
                      Auto-generated
                    </p>
                  </div>
                )}

                <div>
                  <label style={{
                    display: 'block',
                    fontSize: '13px',
                    fontWeight: 'bold',
                    marginBottom: '8px',
                    color: '#333'
                  }}>
                    Status
                  </label>
                  <select
                    value={formData.status}
                    onChange={(e) => handleChange('status', e.target.value as BillingFeeAgreementStatus)}
                    style={{
                      width: '100%',
                      padding: '10px',
                      border: '1px solid #ddd',
                      borderRadius: '6px',
                      fontSize: '14px'
                    }}
                  >
                    <option value={BillingFeeAgreementStatus.ACTIVE}>Active</option>
                    <option value={BillingFeeAgreementStatus.PENDING}>Pending</option>
                    <option value={BillingFeeAgreementStatus.INACTIVE}>Inactive</option>
                    <option value={BillingFeeAgreementStatus.TERMINATED}>Terminated</option>
                  </select>
                </div>
              </div>

              <div>
                <label style={{
                  display: 'block',
                  fontSize: '13px',
                  fontWeight: 'bold',
                  marginBottom: '8px',
                  color: '#333'
                }}>
                  Effective Date *
                </label>
                <input
                  type="date"
                  value={formData.effectiveDate ? new Date(formData.effectiveDate).toISOString().split('T')[0] : ''}
                  onChange={(e) => handleChange('effectiveDate', e.target.value ? new Date(e.target.value) : new Date())}
                  style={{
                    width: '100%',
                    padding: '10px',
                    border: '1px solid #ddd',
                    borderRadius: '6px',
                    fontSize: '14px'
                  }}
                />
              </div>
            </div>

            {/* Billing Configuration */}
            <div style={{ marginBottom: '24px' }}>
              <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '16px', color: '#333' }}>
                Billing Configuration
              </h3>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                <div>
                  <label style={{
                    display: 'block',
                    fontSize: '13px',
                    fontWeight: 'bold',
                    marginBottom: '8px',
                    color: '#333'
                  }}>
                    Billing Frequency
                  </label>
                  <select
                    value={formData.billingFrequency}
                    onChange={(e) => handleChange('billingFrequency', e.target.value as BillingFrequency)}
                    style={{
                      width: '100%',
                      padding: '10px',
                      border: '1px solid #ddd',
                      borderRadius: '6px',
                      fontSize: '14px'
                    }}
                  >
                    <option value={BillingFrequency.QUARTERLY}>Quarterly</option>
                    <option value={BillingFrequency.SEMI_ANNUAL}>Semi-Annual</option>
                    <option value={BillingFrequency.ANNUAL}>Annual</option>
                    <option value={BillingFrequency.MONTHLY}>Monthly</option>
                  </select>
                </div>

                <div>
                  <label style={{
                    display: 'block',
                    fontSize: '13px',
                    fontWeight: 'bold',
                    marginBottom: '8px',
                    color: '#333'
                  }}>
                    Billing Method
                  </label>
                  <select
                    value={formData.billingMethod}
                    onChange={(e) => handleChange('billingMethod', e.target.value as BillingMethod)}
                    style={{
                      width: '100%',
                      padding: '10px',
                      border: '1px solid #ddd',
                      borderRadius: '6px',
                      fontSize: '14px'
                    }}
                  >
                    <option value={BillingMethod.ARREARS}>Arrears</option>
                    <option value={BillingMethod.ADVANCE}>Advance</option>
                  </select>
                </div>
              </div>
            </div>

            {/* Scope - Households & Accounts */}
            <div style={{ marginBottom: '24px' }}>
              <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '16px', color: '#333' }}>
                Households & Account Fee Schedules *
              </h3>

              <div style={{ marginBottom: '16px' }}>
                <p style={{ fontSize: '13px', color: '#666', marginBottom: '12px' }}>
                  Select households, then assign a fee schedule to each account within those households. Only households without active billing agreements are shown.
                </p>

                {errors.households && (
                  <div style={{ display: 'flex', alignItems: 'center', gap: '4px', marginBottom: '12px', padding: '10px', backgroundColor: '#fff3f3', border: '1px solid #f44336', borderRadius: '6px', color: '#f44336', fontSize: '13px' }}>
                    <AlertCircle size={16} />
                    {errors.households}
                  </div>
                )}

                <div style={{
                  border: '1px solid #ddd',
                  borderRadius: '6px',
                  maxHeight: '500px',
                  overflowY: 'auto',
                  backgroundColor: '#fafafa'
                }}>
                  {households.length === 0 ? (
                    <div style={{ padding: '24px', textAlign: 'center', color: '#999', fontSize: '14px' }}>
                      No available households. All households already have active billing fee agreements.
                    </div>
                  ) : (
                    households.map(household => {
                      const isSelected = selectedHouseholdIds.has(household.id);
                      const householdAccounts = allAccounts.filter(acc => acc.householdId === household.id);
                      const accountMappings = householdAccountFeeSchedules[household.id] || {};
                      const totalValue = householdAccounts.reduce((sum, acc) => sum + (acc.currentBalance || 0), 0);

                      return (
                        <div
                          key={household.id}
                          style={{
                            borderBottom: '1px solid #e0e0e0',
                            backgroundColor: isSelected ? '#f0f7ff' : '#fff'
                          }}
                        >
                          {/* Household Header */}
                          <div style={{ padding: '16px', cursor: 'pointer' }}>
                            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
                              {/* Household Checkbox */}
                              <input
                                type="checkbox"
                                checked={isSelected}
                                onChange={() => handleHouseholdToggle(household.id)}
                                style={{
                                  marginTop: '4px',
                                  width: '20px',
                                  height: '20px',
                                  cursor: 'pointer'
                                }}
                              />

                              {/* Household Info */}
                              <div style={{ flex: 1 }}>
                                <div style={{
                                  fontSize: '15px',
                                  fontWeight: 'bold',
                                  color: '#1a1a1a',
                                  marginBottom: '4px'
                                }}>
                                  {household.householdName}
                                </div>
                                <div style={{ fontSize: '12px', color: '#666' }}>
                                  {householdAccounts.length} account{householdAccounts.length !== 1 ? 's' : ''} | Total Value: ${totalValue.toLocaleString()}
                                </div>
                              </div>
                            </div>
                          </div>

                          {/* Accounts within Household (only shown when household is selected) */}
                          {isSelected && householdAccounts.length > 0 && (
                            <div style={{ backgroundColor: '#f8f9fa', padding: '12px 16px 16px 48px' }}>
                              <div style={{
                                fontSize: '13px',
                                fontWeight: 'bold',
                                color: '#555',
                                marginBottom: '12px'
                              }}>
                                Assign Fee Schedules to Accounts:
                              </div>
                              {householdAccounts.map(account => {
                                const feeScheduleId = accountMappings[account.id] || '';
                                const hasError = errors[`account_${account.id}`];

                                return (
                                  <div
                                    key={account.id}
                                    style={{
                                      marginBottom: '12px',
                                      padding: '12px',
                                      backgroundColor: '#fff',
                                      borderRadius: '6px',
                                      border: `1px solid ${hasError ? '#f44336' : '#e0e0e0'}`
                                    }}
                                  >
                                    <div style={{
                                      fontSize: '13px',
                                      fontWeight: 'bold',
                                      color: '#333',
                                      marginBottom: '6px'
                                    }}>
                                      {account.accountNumber} - {account.accountName || account.registrationName || 'Unnamed Account'}
                                    </div>
                                    <div style={{ fontSize: '11px', color: '#666', marginBottom: '8px' }}>
                                      Client: {account.clientName || 'Unknown'} | Balance: ${(account.currentBalance || 0).toLocaleString()}
                                    </div>
                                    <select
                                      value={feeScheduleId}
                                      onChange={(e) => handleAccountFeeScheduleChange(household.id, account.id, e.target.value)}
                                      style={{
                                        width: '100%',
                                        padding: '8px',
                                        border: `1px solid ${hasError ? '#f44336' : '#ddd'}`,
                                        borderRadius: '4px',
                                        fontSize: '13px',
                                        backgroundColor: '#fff'
                                      }}
                                    >
                                      <option value="">Select fee schedule...</option>
                                      {feeSchedules.map(schedule => (
                                        <option key={schedule.id} value={schedule.id}>
                                          {schedule.code} - {schedule.name}
                                        </option>
                                      ))}
                                    </select>
                                    {hasError && (
                                      <div style={{ display: 'flex', alignItems: 'center', gap: '4px', marginTop: '4px', color: '#f44336', fontSize: '11px' }}>
                                        <AlertCircle size={12} />
                                        {hasError}
                                      </div>
                                    )}
                                  </div>
                                );
                              })}
                            </div>
                          )}
                        </div>
                      );
                    })
                  )}
                </div>

                <p style={{ fontSize: '12px', color: '#999', marginTop: '8px' }}>
                  Selected: {selectedHouseholdIds.size} household{selectedHouseholdIds.size !== 1 ? 's' : ''}
                </p>
              </div>

              <div style={{ marginBottom: '16px' }}>
                <label style={{
                  display: 'block',
                  fontSize: '13px',
                  fontWeight: 'bold',
                  marginBottom: '8px',
                  color: '#333'
                }}>
                  Relationship (Optional)
                </label>
                <select
                  value={formData.relationshipId || ''}
                  onChange={(e) => handleChange('relationshipId', e.target.value || undefined)}
                  style={{
                    width: '100%',
                    padding: '10px',
                    border: '1px solid #ddd',
                    borderRadius: '6px',
                    fontSize: '14px'
                  }}
                >
                  <option value="">No relationship</option>
                  {relationships.map(rel => (
                    <option key={rel.id} value={rel.id}>
                      {rel.relationshipName}
                    </option>
                  ))}
                </select>
                <p style={{ fontSize: '12px', color: '#999', marginTop: '4px' }}>
                  Link this agreement to a relationship for better organization
                </p>
              </div>

            </div>

            {/* Fee Adjustment */}
            <div style={{ marginBottom: '24px' }}>
              <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '16px', color: '#333' }}>
                Fee Adjustment (Optional)
              </h3>

              <div style={{ marginBottom: '16px' }}>
                <label style={{
                  display: 'block',
                  fontSize: '13px',
                  fontWeight: 'bold',
                  marginBottom: '8px',
                  color: '#333'
                }}>
                  Custom Fee Adjustment (%)
                </label>
                <input
                  type="number"
                  step="0.01"
                  value={formData.customFeeAdjustment || ''}
                  onChange={(e) => handleChange('customFeeAdjustment', e.target.value ? parseFloat(e.target.value) : undefined)}
                  placeholder="e.g., -10 for 10% discount"
                  style={{
                    width: '100%',
                    padding: '10px',
                    border: '1px solid #ddd',
                    borderRadius: '6px',
                    fontSize: '14px'
                  }}
                />
                <p style={{ fontSize: '12px', color: '#999', marginTop: '4px' }}>
                  Enter negative value for discount, positive for increase
                </p>
              </div>

              <div>
                <label style={{
                  display: 'block',
                  fontSize: '13px',
                  fontWeight: 'bold',
                  marginBottom: '8px',
                  color: '#333'
                }}>
                  Adjustment Notes
                </label>
                <textarea
                  value={formData.customFeeAdjustmentNotes || ''}
                  onChange={(e) => handleChange('customFeeAdjustmentNotes', e.target.value)}
                  placeholder="Reason for fee adjustment..."
                  rows={2}
                  style={{
                    width: '100%',
                    padding: '10px',
                    border: '1px solid #ddd',
                    borderRadius: '6px',
                    fontSize: '14px',
                    fontFamily: 'inherit',
                    resize: 'vertical'
                  }}
                />
              </div>
            </div>

            {/* Notes */}
            <div>
              <label style={{
                display: 'block',
                fontSize: '13px',
                fontWeight: 'bold',
                marginBottom: '8px',
                color: '#333'
              }}>
                Notes
              </label>
              <textarea
                value={formData.notes}
                onChange={(e) => handleChange('notes', e.target.value)}
                placeholder="Additional notes about this billing agreement..."
                rows={3}
                style={{
                  width: '100%',
                  padding: '10px',
                  border: '1px solid #ddd',
                  borderRadius: '6px',
                  fontSize: '14px',
                  fontFamily: 'inherit',
                  resize: 'vertical'
                }}
              />
            </div>
          </div>

          {/* Footer */}
          <div style={{
            padding: '16px 24px',
            borderTop: '1px solid #e0e0e0',
            display: 'flex',
            gap: '12px',
            justifyContent: 'flex-end'
          }}>
            <button
              type="button"
              onClick={onClose}
              style={{
                padding: '10px 24px',
                border: '1px solid #ddd',
                background: 'white',
                borderRadius: '6px',
                cursor: 'pointer',
                fontSize: '14px',
                fontWeight: 'bold',
                color: '#666'
              }}
            >
              Cancel
            </button>
            <button
              type="submit"
              style={{
                padding: '10px 24px',
                border: 'none',
                background: '#2196f3',
                color: 'white',
                borderRadius: '6px',
                cursor: 'pointer',
                fontSize: '14px',
                fontWeight: 'bold'
              }}
            >
              {agreement ? 'Save Changes' : 'Create Agreement'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default BillingFeeAgreementFormModal;
